### ISSUE TITLE
The "url" argument must be of type string. Received type object

### ISSUE THREAD

**Issue by da2x** [datproject/dat-store#11] opened 2019-04-14 22:25 UTC
dat store add dat://daniel.priv.no/

    TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type object
        at Url.parse (url.js:154:11)
        at urlParse (url.js:148:13)
        at /usr/lib/node_modules/dat-store/node_modules/dat-pinning-service-client/index.js:143:16
        at DatPinningServiceClient.addDat (/usr/lib/node_modules/dat-store/node_modules/dat-pinning-service-client/index.js:90:90)
        at Promise (internal/util.js:275:30)
        at new Promise (<anonymous>)
        at DatPinningServiceClient.addDat (internal/util.js:274:12)
        at StoreClient.callClient (/usr/lib/node_modules/dat-store/client.js:67:48)
        at StoreClient.add (/usr/lib/node_modules/dat-store/client.js:116:17)
        at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by RangerMauve** [comment] 2019-04-14 22:51
What version of dat-store and dat-js do you have?

**Comment by da2x** [comment] 2019-04-15 08:23
$ dat -v
    > 13.12.2
    $ dat store -v
    > dat-store add <url>
    >
    > Add a Dat to your storage provider.
    >
    > Options:
    >  --version  Show version number            [boolean]
    >  --help     Show help                      [boolean]
    >
    > Not enough non-option arguments: got 0, need at least 1
    $ dat store --version
    > 1.0.2

**Comment by RangerMauve** [comment] 2019-04-15 15:24
I think the problem is that you didn't run a store locally and didn't configure a remote store.

I'll add a better error message.

In the meantime, you can run one of the following:

```shell
# Run a store in a process
# Will close when you exit
dat store run-service

# Install the store as a service on Linux or Windows
dat store install-service
# You can uninstall it later with
dat store uninstall-service
```

**Comment by RangerMauve** [comment] 2019-04-15 16:04
This should be addressed by https://github.com/datproject/dat-store/commit/27312d7b334f55fe961bfcc06f57b992cbe526c1

**Closed by RangerMauve** 2019-04-15 16:04 UTC

**Comment by da2x** [comment] 2019-04-15 20:05
If you run `dat store` then you’re not given any information other than the add command.

**Comment by RangerMauve** [comment] 2019-04-15 20:07
That's because the default command is `dat store add`. Use `dat store --help` for the full info.

**Comment by RangerMauve** [comment] 2019-04-15 20:07
I suggest also going over the README
